name: Build and publish package

on:
  schedule:
    - cron: "0 12 * * 3"
  workflow_dispatch:

jobs:
  build_publish:
    name: "Build"
    runs-on: docker
    container:
      image: archlinux:latest
    steps:
      - name: Install deps
        run: pacman --noconfirm -Sy git nodejs curl docker docker-buildx

      - name: Wait for Docker daemon
        run: |
          for i in {1..30}; do
            if docker info > /dev/null 2>&1; then
              echo "Docker is ready!"
              break
            fi
            echo "Waiting for Docker to be ready..."
            sleep 1
          done

      - name: Check Docker service logs
        run: curl -s docker:2375/version || echo "dockerd might have failed"

      - name: Docker check
        run: docker info

      - uses: actions/checkout@v4

      - name: Login to the registry
        run: docker login -u landsj -p ${{ secrets.DOCKERHUB }}

      - name: Build
        run: cd docker && docker build -t landsj/tempsystem .

      - name: Push
        run: cd docker && docker push landsj/tempsystem
