name: Build and publish package

on:
  schedule:
    - cron: "0 12 * * 3"
  workflow_dispatch:

jobs:
  build_publish:
    name: "Build"
    runs-on: docker
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
    steps:
      - run: apt-get update && apt-get install buildah ca-certificates -y
      - uses: actions/checkout@v4
      - uses: https://codeberg.org/actions/buildah-simple@main
        with:
          tag: "docker.io/landsj/tempsystem:latest"
          context: .
          push: true
          username: "landsj"
          password: ${{ secrets.DOCKERHUB }}
          registry: "docker.io"
