# ZSH setup
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="gentoo"

plugins=(
	git
	zsh-syntax-highlighting
	zsh-autosuggestions
	fzf
	sudo
	archlinux
	rust
	command-not-found
)

if [ -e "$ZSH/oh-my-zsh.sh" ]; then
	source $ZSH/oh-my-zsh.sh
fi

# For unsupported terminals
export TERM=xterm-256color

# Common aliases
alias rm="rm -v"
alias cp="cp -v"
alias mv="mv -v"
alias ls="eza --icons=auto"
alias lss="eza --sort=date --icons=auto"

# Show the welcome message
if [[ "$SHOW_WELCOME" == "true" ]]; then
	figlet Welcome | lolcat
	echo The base image for tempsystem is archlinux:latest, so:
	echo - - use \"sudo pacman -S program\" to install archlinux packages.
	echo - - use \"yay -S program\" to install AUR packages.
fi